//
//  DetailsCountryViewController.swift
//  CountryInfo
//
//  Created Paulo Henrique Oliveira Souza on 24/06/2018.
//  Copyright © 2018 Paulo. All rights reserved.
//
//  Template generated by Paulo Henrique Oliviera Souza @-Lelouch
//

import UIKit
import SVGKit

class DetailsCountryViewController: UIViewController{
    
    @IBOutlet weak var name: UILabel!
    @IBOutlet weak var nativeName: UILabel!
    @IBOutlet weak var Capital: UILabel!
    @IBOutlet weak var region: UILabel!
    @IBOutlet weak var subregion: UILabel!
    @IBOutlet weak var pupolation: UILabel!
    @IBOutlet weak var numericCode: UILabel!
    
    @IBOutlet weak var flag: UIImageView!
    @IBOutlet weak var activityIndicator: UIActivityIndicatorView!
    
    var presenter: DetailsCountryPresenterProtocol?
    
    var country: CountryEntity?
    
    override func viewDidLoad() {
        super.viewDidLoad()
        self.navigationItem.title = "\(country!.name ?? "Details")"
        self.activityIndicator.startAnimating()
        self.setupFields()
        self.presenter?.downloadImage(url: self.country!.flagURL ?? "")
    }
    
    private func setupFields(){
        self.name.text = "Name: \(country!.name ?? "")"
        self.nativeName.text = "NativeName: \(country!.nativeName ?? "")"
        self.Capital.text = "Capital: \(country!.capital ?? "")"
        self.region.text = "Region: \(country!.region ?? "")"
        self.subregion.text = "Subregion: \(country!.subregion ?? "")"
        self.pupolation.text = "Pupolation: \(country!.population ?? 0)"
        self.numericCode.text = "Numeri Code: \(country!.numericCode ?? "")"
        
    }
    
}

extension DetailsCountryViewController : DetailsCountryViewProtocol {
    func showImage(image: UIImage) {
        self.activityIndicator.stopAnimating()
        self.activityIndicator.isHidden = true
        self.flag.image = image
    }
    
    func showErrorAlert() {
         self.showAlert(withMessage: "Whoops... something went wrong")
    }
}
