//
//  DetailsCountryInteractor.swift
//  CountryInfo
//
//  Created Paulo Henrique Oliveira Souza on 24/06/2018.
//  Copyright © 2018 Paulo. All rights reserved.
//
//  Template generated by Paulo Henrique Oliviera Souza @-Lelouch
//

import UIKit
import SVGKit

class DetailsCountryInteractor {
    
    var presenter: DetailsCountryPresenterProtocol?
    
    func loadImage(with url: String){
        DispatchQueue.global().async {
            if let documentURL = URL(string:   url),
                let data = try? Data(contentsOf: documentURL),
                let image = SVGKImage(data: data) {
                DispatchQueue.main.async {
                    self.presenter?.didRetrieveImage(image: image.uiImage)
                }
                
                
            } else {
                DispatchQueue.main.async {
                    self.presenter?.didRetrieveError()

                }
            }
        }

        
    }
    
}

extension DetailsCountryInteractor: DetailsCountryInteractorProtocol {
    func downloadImage(url: String) {
        self.loadImage(with: url)
    }
}
