//
//  DetailsCountryProtocols.swift
//  CountryInfo
//
//  Created Paulo Henrique Oliveira Souza on 24/06/2018.
//  Copyright © 2018 Paulo. All rights reserved.
//
//  Template generated by Paulo Henrique Oliviera Souza @-Lelouch
//

import Foundation
import UIKit
//MARK: Router -
protocol DetailsCountryRouterProtocol {

}
//MARK: Presenter -
protocol DetailsCountryPresenterProtocol {
    //func didLoad()
    func downloadImage(url: String)
    func didRetrieveError()
    func didRetrieveImage(image: UIImage)

}

//MARK: Interactor -
protocol DetailsCountryInteractorProtocol {
    func downloadImage(url: String)
}

//MARK: View -
protocol DetailsCountryViewProtocol {

    func showImage(image: UIImage)
    func showErrorAlert()
}
