//
//  HomePresenter.swift
//  CountryInfo
//
//  Created Paulo Henrique Oliveira Souza on 24/06/2018.
//  Copyright © 2018 Paulo. All rights reserved.
//
//  Template generated by Paulo Henrique Oliviera Souza @-Lelouch
//

import UIKit

class HomePresenter {
    
    private var view: HomeViewProtocol?
    var interactor: HomeInteractorProtocol?
    private let router: HomeRouterProtocol
    
    init(interface: HomeViewProtocol, interactor: HomeInteractorProtocol?, router: HomeRouterProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

}

extension HomePresenter: HomePresenterProtocol {

    func didLoad() {
        self.view?.showLoading(show: true)
        self.interactor?.loadCountries()
    }
    
    func didRetrieveCountries(countries: [CountryEntity]) {
        self.view?.showCountries(countries: countries)
    }
    
    func didRetrieveError() {
        
    }
    
    func didSelectedCountry(country: CountryEntity) {
        self.router.showCountryDetails(country: country)
    }
    
    
}
