//
//  HomeRouter.swift
//  CountryInfo
//
//  Created Paulo Henrique Oliveira Souza on 24/06/2018.
//  Copyright © 2018 Paulo. All rights reserved.
//
//  Template generated by Paulo Henrique Oliviera Souza @-Lelouch
//

import UIKit

class HomeRouter: BaseRouter {
    
    static func makeController() -> HomeTableViewController {
        
        let storyBoad = UIStoryboard(name: "MainInterface", bundle: nil)
        let view = storyBoad.instantiateViewController(withIdentifier: "HomeTableViewController") as! HomeTableViewController
        let interactor = HomeInteractor()
        let router = HomeRouter(viewController: view)
        let presenter = HomePresenter(interface: view, interactor: interactor, router: router)
        
        view.presenter = presenter
        interactor.presenter = presenter
        
        return view
    }
}

extension HomeRouter: HomeRouterProtocol {
    func showCountryDetails(country: CountryEntity) {
        self.pushModule(viewController: DetailsCountryRouter.makeController(parameter: ParameterIO(withObject: country)), animated: true)
    }
}
