//
//  HomeProtocols.swift
//  CountryInfo
//
//  Created Paulo Henrique Oliveira Souza on 24/06/2018.
//  Copyright © 2018 Paulo. All rights reserved.
//
//  Template generated by Paulo Henrique Oliviera Souza @-Lelouch
//

import Foundation

//MARK: Router -
protocol HomeRouterProtocol {
    
    func showCountryDetails(country: CountryEntity)

}
//MARK: Presenter -
protocol HomePresenterProtocol {
    func didLoad()
    func didRetrieveCountries(countries: [CountryEntity])
    func didRetrieveError()
    func didSelectedCountry(country: CountryEntity)
}

//MARK: Interactor -
protocol HomeInteractorProtocol {

    func loadCountries()
    
}

//MARK: View -
protocol HomeViewProtocol {

    func showCountries(countries: [CountryEntity])
    func showErrorAlert()
    func showLoading(show: Bool)
    
}
