//
//  HomeInteractor.swift
//  CountryInfo
//
//  Created Paulo Henrique Oliveira Souza on 24/06/2018.
//  Copyright © 2018 Paulo. All rights reserved.
//
//  Template generated by Paulo Henrique Oliviera Souza @-Lelouch
//

import UIKit

class HomeInteractor {
    
    var presenter: HomePresenterProtocol?
    
    fileprivate func getCountries() {
        
        Service.shared.request(request: CoutryRequest(), completion: { (countries: [CountryEntity]?) in
            
            if let countries = countries {
                self.presenter?.didRetrieveCountries(countries: countries)
                return
            }
            self.presenter?.didRetrieveError()
            
        }) { (error) in
            self.presenter?.didRetrieveError()
        }
        
    }
    
}

extension HomeInteractor: HomeInteractorProtocol {
    func loadCountries() {
        self.getCountries()
    }
}
