//
//  DetailsCountryPresenter.swift
//  CountryInfo
//
//  Created Paulo Henrique Oliveira Souza on 24/06/2018.
//  Copyright © 2018 Paulo. All rights reserved.
//
//  Template generated by Paulo Henrique Oliviera Souza @-Lelouch
//

import UIKit

class DetailsCountryPresenter {
    
    private var view: DetailsCountryViewProtocol?
    var interactor: DetailsCountryInteractorProtocol?
    private let router: DetailsCountryRouterProtocol
    
    init(interface: DetailsCountryViewProtocol, interactor: DetailsCountryInteractorProtocol?, router: DetailsCountryRouterProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }
    
}

extension DetailsCountryPresenter: DetailsCountryPresenterProtocol {
    func didRetrieveError() {
        self.view?.showErrorAlert()
    }
    
    func didRetrieveImage(image: UIImage) {
        self.view?.showImage(image: image)
    }
    
    func downloadImage(url: String) {
        self.interactor?.downloadImage(url: url)
    }
    
}
